### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rs-natano** [jbg/rabbitmq#1]
If you are ok with other people using this library (or building upon it), it would be nice if you add a license to the code, so it can be used without running into legal issue. Permissive licenses like MIT, BSD or ISC preferred, but of course it is your choice. :)

**Comment by jbg** [comment]
Thanks for the heads up! It's under the Apache License 2.0, I've added a license file and a header to the source file.

**Comment by rs-natano** [comment]
Thanks! That was fast. :)
